[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[tool.poetry]
name = "nexios"
version = "0.1.1"
description = "Nexio is a modern, high-performance ASGI web framework for Python."
authors = ["Chidebele Dunamis <techwithdunamix@example.com>"]
license = "MIT"
homepage = "https://github.com/techwithdunamix/nexio"
repository = "https://github.com/techwithdunamix/nexio"
readme = "readme.md"

[tool.poetry.dependencies]
python = ">=3.8"



