[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[tool.poetry]
name = "nexios"
version = "0.1.24"
description = "Nexio is a modern, high-performance ASGI web framework for Python."
authors = ["Chidebele Dunamis <techwithdunamix@example.com>"]
license = "MIT"
homepage = "https://github.com/techwithdunamix/nexios"
repository = "https://github.com/techwithdunamix/nexios"
readme = "readme.md"

[tool.poetry.dependencies]
python = ">=3.8"
tortoise-orm = "*"
uvicorn = "*"
aerich = "*"
asgiref = "*"
anyio = "*"
aiofiles = "*"
itsdangerous = "*"

[tool.poetry.scripts]
nexios = "nexios.cli.main:main"


