site_name: Nexios
site_description: A modern backend framework for building scalable and efficient web applications.
site_author: Dunamis
site_url: https://nexios.example.com
repo_url: https://github.com/techwithdunamix/nexios

# Theme Configuration
theme:
  # name: united
  name: material
  favicon: logo.png
  logo: logo.png
  palette:
    - scheme: light
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/brightness-1 
        name: Switch to dark mode
    - scheme: dark
      primary: deep-orange
      accent: deep-orange
  syntax:
    highlight: true 
  toggle:
    icon: material/weather-night  # Icon for the toggle button
    name: Toggle theme
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.instant.progress
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  plugins:
    - blog

# Navigation Structure
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: introduction.md
      - Installation: installation.md
      - Hello World : hello_world.md
      - Routing : basic_routing.md
      
  - Guide:
    - guides/routing.md
    - guides/nexio-request.md
    - guides/nexio-response.md
  - Core Features:
      - Request Object: core-features/request-object.md
      - Response Object: core-features/response-object.md
      - Middleware: core-features/middleware.md
      - Router: core-features/router.md
      - Routing: core-features/routing.md
      - WebSocket Support: core-features/websocket.md
      - Session Management: core-features/session-manager.md
      - Validators: core-features/validators.md
  - Integrations:
      - Tortoise ORM: integrations/tortoise-orm.md
      - Redis: integrations/redis.md
      - Celery: integrations/celery.md
  - Tutorials:
      - Basic Application: tutorials/basic-app.md
      - Real-Time Chat with WebSockets: tutorials/realtime-chat.md
      - REST API with ORM: tutorials/rest-api.md
      - Authentication System: tutorials/authentication.md
  - API Reference:
      - Nexios API: api-reference/nexios.md
      - Middleware API: api-reference/middleware.md
      - Router API: api-reference/router.md
      - Validators API: api-reference/validators.md
  - Advanced Guides:
      - Custom Middleware: advanced/custom-middleware.md
      - Extending the Router: advanced/extending-router.md
      - Writing Custom Validators: advanced/custom-validators.md

# Plugins
plugins:
  - blog
  - offline
  - git-revision-date-localized:
      enable: true
  - multirepo
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true


extra:
  seo:
    description: A detailed description of your website for SEO.
    keywords: nexios, nexios python, dunamis, nexios backend
  generator: false
  version:
    provider: mike
    default: stable 
  social:
    - icon: fontawesome/brands/medium 
      link: https://medium.com/@techwithdunamix
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
copyright: Copyright &copy; 2024 Techwithdunamix
